
let
    Source = FactClientWorkflow,

    KeepColumns =
        Table.SelectColumns(
            Source,
            {
                "WorkflowKey",
                "apptmnt_type",
                "rqst_rcvd",
                "app_rcvd",
                "app_mgmt_comp",
                "checklist_complete",
                "verif_complete",
                "sent_to_client",
                "prior_appt_end"
            }
        ),

    TodayDate = Date.From(DateTime.LocalNow()),

    BusinessDays = (StartDate as nullable date, EndDate as nullable date) as nullable number =>
        if StartDate = null then 0
        else
            let
                ActualEnd = if EndDate = null then TodayDate else EndDate,
                SafeEnd = if ActualEnd < StartDate then StartDate else ActualEnd,
                DateList = List.Dates(StartDate, Duration.Days(SafeEnd - StartDate) + 1, #duration(1, 0, 0, 0)),
                BusinessDayList = List.Select(DateList, each Date.DayOfWeek(_, Day.Monday) < 5),
                CountDays = List.Count(BusinessDayList)
            in
                CountDays,

    SLA1 =
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Table.AddColumn(KeepColumns, "SLAStageKey", each 1, Int64.Type),
                    "StageStartDate", each [rqst_rcvd], type date
                ),
                "StageEndDate", each [app_rcvd], type date
            ),
            "StageElapsedDays", each BusinessDays([rqst_rcvd], [app_rcvd]), Int64.Type
        ),

    SLA2 =
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Table.AddColumn(KeepColumns, "SLAStageKey", each 2, Int64.Type),
                    "StageStartDate", each [app_rcvd], type date
                ),
                "StageEndDate", each [app_mgmt_comp], type date
            ),
            "StageElapsedDays", each BusinessDays([app_rcvd], [app_mgmt_comp]), Int64.Type
        ),

    SLA3 =
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Table.AddColumn(KeepColumns, "SLAStageKey", each 3, Int64.Type),
                    "StageStartDate", each [app_mgmt_comp], type date
                ),
                "StageEndDate", each [checklist_complete], type date
            ),
            "StageElapsedDays", each BusinessDays([app_mgmt_comp], [checklist_complete]), Int64.Type
        ),

    SLA4 =
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Table.AddColumn(KeepColumns, "SLAStageKey", each 4, Int64.Type),
                    "StageStartDate", each [checklist_complete], type date
                ),
                "StageEndDate", each [verif_complete], type date
            ),
            "StageElapsedDays", each BusinessDays([checklist_complete], [verif_complete]), Int64.Type
        ),

    SLA5Start =
        Table.AddColumn(
            KeepColumns,
            "SLA5StartDate",
            each
                if [checklist_complete] = null or [verif_complete] = null then null
                else List.Max({[checklist_complete], [verif_complete]}),
            type date
        ),

    SLA5 =
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Table.AddColumn(SLA5Start, "SLAStageKey", each 5, Int64.Type),
                    "StageStartDate", each [SLA5StartDate], type date
                ),
                "StageEndDate", each [sent_to_client], type date
            ),
            "StageElapsedDays", each BusinessDays([SLA5StartDate], [sent_to_client]), Int64.Type
        ),

    SLA6 =
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Table.AddColumn(KeepColumns, "SLAStageKey", each 6, Int64.Type),
                    "StageStartDate", each [checklist_complete], type date
                ),
                "StageEndDate", each [sent_to_client], type date
            ),
            "StageElapsedDays", each BusinessDays([checklist_complete], [sent_to_client]), Int64.Type
        ),

    SLA7 =
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Table.AddColumn(KeepColumns, "SLAStageKey", each 7, Int64.Type),
                    "StageStartDate", each [rqst_rcvd], type date
                ),
                "StageEndDate", each [sent_to_client], type date
            ),
            "StageElapsedDays", each BusinessDays([rqst_rcvd], [sent_to_client]), Int64.Type
        ),

    SLA8 =
        Table.AddColumn(
            Table.AddColumn(
                Table.AddColumn(
                    Table.AddColumn(KeepColumns, "SLAStageKey", each 8, Int64.Type),
                    "StageStartDate", each [prior_appt_end], type date
                ),
                "StageEndDate", each [sent_to_client], type date
            ),
            "StageElapsedDays",
            each
                if [apptmnt_type] = "I" or [prior_appt_end] = null then 0
                else Duration.Days((if [sent_to_client] = null then TodayDate else [sent_to_client]) - [prior_appt_end]),
            Int64.Type
        ),

    AppendAll =
        Table.Combine({SLA1, SLA2, SLA3, SLA4, SLA5, SLA6, SLA7, SLA8}),

    AddStatus =
        Table.AddColumn(
            AppendAll,
            "SLAStatus",
            each
                if [SLAStageKey] = 8 and [apptmnt_type] = "I" then "Not A Recred"
                else if [StageStartDate] = null then "Not In process yet"
                else if [SLAStageKey] = 1 and [StageEndDate] <> null and [StageElapsedDays] > 5 then "Completed Exceeded Time"
                else if [SLAStageKey] = 1 and [StageEndDate] <> null then "Completed On Time"
                else if [SLAStageKey] = 1 and [StageElapsedDays] > 5 then "Open Exceeded Time"
                else if [SLAStageKey] = 1 and [StageElapsedDays] > 3 then "Open At Risk"

                else if [SLAStageKey] = 2 and [StageEndDate] <> null and [StageElapsedDays] > 5 then "Completed Exceeded Time"
                else if [SLAStageKey] = 2 and [StageEndDate] <> null then "Completed On Time"
                else if [SLAStageKey] = 2 and [StageElapsedDays] > 5 then "Open Exceeded Time"
                else if [SLAStageKey] = 2 and [StageElapsedDays] > 3 then "Open At Risk"

                else if [SLAStageKey] = 3 and [StageEndDate] <> null and [StageElapsedDays] > 15 then "Completed Exceeded Time"
                else if [SLAStageKey] = 3 and [StageEndDate] <> null then "Completed On Time"
                else if [SLAStageKey] = 3 and [StageElapsedDays] > 15 then "Open Exceeded Time"
                else if [SLAStageKey] = 3 and [StageElapsedDays] > 12 then "Open At Risk"

                else if [SLAStageKey] = 4 and [StageEndDate] <> null and [StageElapsedDays] > 10 then "Completed Exceeded Time"
                else if [SLAStageKey] = 4 and [StageEndDate] <> null then "Completed On Time"
                else if [SLAStageKey] = 4 and [StageElapsedDays] > 10 then "Open Exceeded Time"
                else if [SLAStageKey] = 4 and [StageElapsedDays] > 7 then "Open At Risk"

                else if [SLAStageKey] = 5 and [StageEndDate] <> null and [StageElapsedDays] > 4 then "Completed Exceeded Time"
                else if [SLAStageKey] = 5 and [StageEndDate] <> null then "Completed On Time"
                else if [SLAStageKey] = 5 and [StageElapsedDays] > 4 then "Open Exceeded Time"
                else if [SLAStageKey] = 5 and [StageElapsedDays] > 2 then "Open At Risk"

                else if [SLAStageKey] = 6 and [StageEndDate] <> null and [StageElapsedDays] > 30 then "Completed Exceeded Time"
                else if [SLAStageKey] = 6 and [StageEndDate] <> null then "Completed On Time"
                else if [SLAStageKey] = 6 and [StageElapsedDays] > 30 then "Open Exceeded Time"
                else if [SLAStageKey] = 6 and [StageElapsedDays] > 25 then "Open At Risk"

                else if [SLAStageKey] = 7 and [StageEndDate] <> null and [StageElapsedDays] > 30 then "Completed Exceeded Time"
                else if [SLAStageKey] = 7 and [StageEndDate] <> null then "Completed On Time"
                else if [SLAStageKey] = 7 and [StageElapsedDays] > 30 then "Open Exceeded Time"
                else if [SLAStageKey] = 7 and [StageElapsedDays] > 25 then "Open At Risk"

                else if [SLAStageKey] = 8 and [prior_appt_end] = null then "No Prior Recred Date"
                else if [SLAStageKey] = 8 and [StageEndDate] <> null and [StageElapsedDays] > 0 then "Completed Exceeded Date"
                else if [SLAStageKey] = 8 and [StageEndDate] <> null then "Completed On Time"
                else if [SLAStageKey] = 8 and [StageElapsedDays] > 0 then "Open Exceeded Date"
                else if [SLAStageKey] = 8 and [StageElapsedDays] > -5 then "Open At Risk"

                else "Open",
            type text
        ),

    AddIsCompleted =
        Table.AddColumn(
            AddStatus,
            "IsCompleted",
            each Text.StartsWith([SLAStatus], "Completed"),
            type logical
        ),

    AddIsOnTime =
        Table.AddColumn(
            AddIsCompleted,
            "IsOnTime",
            each [SLAStatus] = "Completed On Time",
            type logical
        ),

    AddIsAtRisk =
        Table.AddColumn(
            AddIsOnTime,
            "IsAtRisk",
            each [SLAStatus] = "Open At Risk",
            type logical
        ),

    AddIsOutOfCompliance =
        Table.AddColumn(
            AddIsAtRisk,
            "IsOutOfCompliance",
            each Text.Contains([SLAStatus], "Exceeded"),
            type logical
        ),

    Final =
        Table.SelectColumns(
            AddIsOutOfCompliance,
            {
                "WorkflowKey",
                "SLAStageKey",
                "StageStartDate",
                "StageEndDate",
                "StageElapsedDays",
                "SLAStatus",
                "IsCompleted",
                "IsOnTime",
                "IsAtRisk",
                "IsOutOfCompliance"
            }
        )
in
    Final
