AddWorkflowKey =
    Table.AddColumn(
        Source,
        "WorkflowKey",
        each
            Text.Combine(
                {
                    Text.From([parent_facility_id]),
                    Text.From([prac_id]),
                    Text.From([npi_number]),
                    if [rqst_rcvd] = null then "" else Date.ToText([rqst_rcvd], "yyyy-MM-dd")
                },
                "|"
            ),
        type text
    )
